package cm_awt;

/*
 *  File        :   Dialog_options.java
 *  Author      :   Tobias Berthold
 *  Date        :   9-20-2001
 *  Description :   Dialog to enter data
 *  Change      :   10-8-2001   save options to text file
 */

import java.awt.*;

public class options_nbody extends java.awt.Dialog  
{
    
    globals g;      // 
    
	public options_nbody(Frame parent)
	{
		super(parent);

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setBackground(java.awt.Color.lightGray);
		setSize(502,382);
		setVisible(false);
		label1.setText("Body");
		add(label1);
		label1.setBounds(12,60,36,12);
		label2.setText("m");
		add(label2);
		label2.setBounds(12,84,24,12);
		label3.setText("x");
		add(label3);
		label3.setBounds(12,120,24,12);
		label4.setText("y");
		add(label4);
		label4.setBounds(12,144,24,12);
		label5.setText("z");
		add(label5);
		label5.setBounds(12,168,24,12);
		label6.setText("1");
		add(label6);
		label6.setBounds(72,60,24,12);
		label7.setText("2");
		add(label7);
		label7.setForeground(java.awt.Color.green);
		label7.setBounds(144,60,24,12);
		label8.setText("3");
		add(label8);
		label8.setForeground(java.awt.Color.blue);
		label8.setBounds(216,60,24,12);
		add(textField_m1);
		textField_m1.setBounds(36,84,72,24);
		add(textField_x1);
		textField_x1.setBounds(36,120,72,24);
		add(textField_y1);
		textField_y1.setBounds(36,144,72,24);
		add(textField_z1);
		textField_z1.setBounds(36,168,72,24);
		button_ok.setLabel("Ok");
		add(button_ok);
		button_ok.setBounds(204,336,60,22);
		label9.setText("vx");
		add(label9);
		label9.setBounds(12,204,24,12);
		label10.setText("vy");
		add(label10);
		label10.setBounds(12,228,24,12);
		label11.setText("vz");
		add(label11);
		label11.setBounds(12,252,24,12);
		add(textField_vx1);
		textField_vx1.setBounds(36,204,72,24);
		add(textField_vy1);
		textField_vy1.setBounds(36,228,72,24);
		add(textField_vz1);
		textField_vz1.setBounds(36,252,72,24);
		add(textField_m2);
		textField_m2.setBounds(120,84,72,24);
		add(textField_x2);
		textField_x2.setBounds(120,120,72,24);
		add(textField_y2);
		textField_y2.setBounds(120,144,72,24);
		add(textField_z2);
		textField_z2.setBounds(120,168,72,24);
		add(textField_vx2);
		textField_vx2.setBounds(120,204,72,24);
		add(textField_vy2);
		textField_vy2.setBounds(120,228,72,24);
		add(textField_vz2);
		textField_vz2.setBounds(120,252,72,24);
		add(textField_m3);
		textField_m3.setBounds(204,84,72,24);
		add(textField_x3);
		textField_x3.setBounds(204,120,72,24);
		add(textField_y3);
		textField_y3.setBounds(204,144,72,24);
		add(textField_z3);
		textField_z3.setBounds(204,168,72,24);
		add(textField_vx3);
		textField_vx3.setBounds(204,204,72,24);
		add(textField_vy3);
		textField_vy3.setBounds(204,228,72,24);
		add(textField_vz3);
		textField_vz3.setBounds(204,252,72,24);
		label12.setText("Zoom");
		add(label12);
		label12.setBounds(324,204,36,12);
		add(textField_zoom);
		textField_zoom.setBounds(384,204,72,24);
		add(textField_tfinal);
		textField_tfinal.setBounds(384,132,72,24);
		label13.setText("t final");
		add(label13);
		label13.setBounds(324,132,36,12);
		label14.setText("t step");
		add(label14);
		label14.setBounds(324,168,36,12);
		add(textField_tstep);
		textField_tstep.setBounds(384,168,72,24);
		radioButton_center1.setCheckboxGroup(Group_center);
		add(radioButton_center1);
		radioButton_center1.setBounds(60,288,24,24);
		label15.setText("Center");
		add(label15);
		label15.setBounds(12,288,36,12);
		radioButton_center2.setCheckboxGroup(Group_center);
		add(radioButton_center2);
		radioButton_center2.setBounds(144,288,24,24);
		radioButton_center3.setCheckboxGroup(Group_center);
		add(radioButton_center3);
		radioButton_center3.setBounds(228,288,24,24);
		radioButton_centerIRF.setCheckboxGroup(Group_center);
		radioButton_centerIRF.setLabel("IRF");
		add(radioButton_centerIRF);
		radioButton_centerIRF.setBounds(288,288,48,24);
		radioButton_centerCM.setCheckboxGroup(Group_center);
		radioButton_centerCM.setLabel("CM");
		add(radioButton_centerCM);
		radioButton_centerCM.setBounds(348,288,48,24);
		radioButton_nbody.setCheckboxGroup(Group_type);
		radioButton_nbody.setLabel("Nbody");
		add(radioButton_nbody);
		radioButton_nbody.setBounds(60,24,60,24);
		label16.setText("Type");
		add(label16);
		label16.setBounds(12,24,36,12);
		radioButton_crtbp.setCheckboxGroup(Group_type);
		radioButton_crtbp.setLabel("CRTBP");
		add(radioButton_crtbp);
		radioButton_crtbp.setBounds(168,24,60,24);
		add(textField_mu);
		textField_mu.setBounds(384,84,72,24);
		label17.setText("Mu");
		add(label17);
		label17.setBounds(324,84,36,12);
		radioButton_hill.setCheckboxGroup(Group_type);
		radioButton_hill.setLabel("Hill");
		add(radioButton_hill);
		radioButton_hill.setBounds(264,24,60,24);
		//}}

		//{{REGISTER_LISTENERS
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		SymAction lSymAction = new SymAction();
		button_ok.addActionListener(lSymAction);
		textField_vy3.addActionListener(lSymAction);
		//}}
		
		// my stuff
		
	}
	
	public options_nbody(Frame parent, boolean modal)
	{
		this(parent);
        setModal(modal);
	}
	
	public void addNotify()
	{
  	    // Record the size of the window prior to calling parents addNotify.
	    Dimension d = getSize();

		super.addNotify();

		if (fComponentsAdjusted)
			return;

		// Adjust components according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + d.width, insets.top + insets.bottom + d.height);
		Component components[] = getComponents();
		for (int i = 0; i < components.length; i++)
		{
			Point p = components[i].getLocation();
			p.translate(insets.left, insets.top);
			components[i].setLocation(p);
		}
		fComponentsAdjusted = true;
	}

    // Used for addNotify check.
	boolean fComponentsAdjusted = false;


	public options_nbody(Frame parent, String title, boolean modal)
	{
		this(parent, modal);
		setTitle(title);
	}

    /**
     * Shows or hides the component depending on the boolean flag b.
     * @param b  if true, show the component; otherwise, hide the component.
     * @see java.awt.Component#isVisible
     */
    public void setVisible(boolean b)
	{
        // my stuff
        if(g!=null)
        {
            // body 1
		    textField_m1.setText(""+g.m1);
		    textField_x1.setText(""+g.X_array[0]);
		    textField_y1.setText(""+g.X_array[1]);
		    textField_z1.setText(""+g.X_array[2]);
		    textField_vx1.setText(""+g.X_array[3]);
		    textField_vy1.setText(""+g.X_array[4]);
		    textField_vz1.setText(""+g.X_array[5]);
            // body 2
		    textField_m2.setText(""+g.m2);
		    textField_x2.setText(""+g.X_array[6]);
		    textField_y2.setText(""+g.X_array[7]);
		    textField_z2.setText(""+g.X_array[8]);
		    textField_vx2.setText(""+g.X_array[9]);
		    textField_vy2.setText(""+g.X_array[10]);
		    textField_vz2.setText(""+g.X_array[11]);
            // body 3
		    textField_m3.setText(""+g.m3);
		    textField_x3.setText(""+g.X_array[12]);
		    textField_y3.setText(""+g.X_array[13]);
		    textField_z3.setText(""+g.X_array[14]);
		    textField_vx3.setText(""+g.X_array[15]);
		    textField_vy3.setText(""+g.X_array[16]);
		    textField_vz3.setText(""+g.X_array[17]);
            // other
		    textField_mu.setText(""+g.mu);
		    textField_zoom.setText(""+g.zoom);
		    textField_tfinal.setText(""+g.t_final);
		    textField_tstep.setText(""+g.t_step);
		    switch(g.origin_display)
		    {
		        case '1': radioButton_center1.setState(true); break;
		        case '2': radioButton_center2.setState(true); break;
		        case '3': radioButton_center3.setState(true); break;
		        case 'I': radioButton_centerIRF.setState(true); break;
		        case 'C': radioButton_centerCM.setState(true); break;
		        default: break;
		    }
		    switch(g.mode)
		    {
		        case 'N': radioButton_nbody.setState(true); break;
		        case 'C': radioButton_crtbp.setState(true); break;
		        case 'H': radioButton_hill.setState(true); break;
		        default: break;
		    }
		}    
		
		
		if(b)
		{
			Rectangle bounds = getParent().getBounds();
			Rectangle abounds = getBounds();
	
			setLocation(bounds.x + (bounds.width - abounds.width)/ 2,
				 bounds.y + (bounds.height - abounds.height)/2);
		}
		super.setVisible(b);
	}

	//{{DECLARE_CONTROLS
	java.awt.Label label1 = new java.awt.Label();
	java.awt.Label label2 = new java.awt.Label();
	java.awt.Label label3 = new java.awt.Label();
	java.awt.Label label4 = new java.awt.Label();
	java.awt.Label label5 = new java.awt.Label();
	java.awt.Label label6 = new java.awt.Label();
	java.awt.Label label7 = new java.awt.Label();
	java.awt.Label label8 = new java.awt.Label();
	java.awt.TextField textField_m1 = new java.awt.TextField();
	java.awt.TextField textField_x1 = new java.awt.TextField();
	java.awt.TextField textField_y1 = new java.awt.TextField();
	java.awt.TextField textField_z1 = new java.awt.TextField();
	java.awt.Button button_ok = new java.awt.Button();
	java.awt.Label label9 = new java.awt.Label();
	java.awt.Label label10 = new java.awt.Label();
	java.awt.Label label11 = new java.awt.Label();
	java.awt.TextField textField_vx1 = new java.awt.TextField();
	java.awt.TextField textField_vy1 = new java.awt.TextField();
	java.awt.TextField textField_vz1 = new java.awt.TextField();
	java.awt.TextField textField_m2 = new java.awt.TextField();
	java.awt.TextField textField_x2 = new java.awt.TextField();
	java.awt.TextField textField_y2 = new java.awt.TextField();
	java.awt.TextField textField_z2 = new java.awt.TextField();
	java.awt.TextField textField_vx2 = new java.awt.TextField();
	java.awt.TextField textField_vy2 = new java.awt.TextField();
	java.awt.TextField textField_vz2 = new java.awt.TextField();
	java.awt.TextField textField_m3 = new java.awt.TextField();
	java.awt.TextField textField_x3 = new java.awt.TextField();
	java.awt.TextField textField_y3 = new java.awt.TextField();
	java.awt.TextField textField_z3 = new java.awt.TextField();
	java.awt.TextField textField_vx3 = new java.awt.TextField();
	java.awt.TextField textField_vy3 = new java.awt.TextField();
	java.awt.TextField textField_vz3 = new java.awt.TextField();
	java.awt.Label label12 = new java.awt.Label();
	java.awt.TextField textField_zoom = new java.awt.TextField();
	java.awt.TextField textField_tfinal = new java.awt.TextField();
	java.awt.Label label13 = new java.awt.Label();
	java.awt.Label label14 = new java.awt.Label();
	java.awt.TextField textField_tstep = new java.awt.TextField();
	java.awt.Checkbox radioButton_center1 = new java.awt.Checkbox();
	java.awt.CheckboxGroup Group_center = new java.awt.CheckboxGroup();
	java.awt.Label label15 = new java.awt.Label();
	java.awt.Checkbox radioButton_center2 = new java.awt.Checkbox();
	java.awt.Checkbox radioButton_center3 = new java.awt.Checkbox();
	java.awt.Checkbox radioButton_centerIRF = new java.awt.Checkbox();
	java.awt.Checkbox radioButton_centerCM = new java.awt.Checkbox();
	java.awt.Checkbox radioButton_nbody = new java.awt.Checkbox();
	java.awt.CheckboxGroup Group_type = new java.awt.CheckboxGroup();
	java.awt.Label label16 = new java.awt.Label();
	java.awt.Checkbox radioButton_crtbp = new java.awt.Checkbox();
	java.awt.TextField textField_mu = new java.awt.TextField();
	java.awt.Label label17 = new java.awt.Label();
	java.awt.Checkbox radioButton_hill = new java.awt.Checkbox();
	//}}

	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowClosed(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == options_nbody.this)
				DialogData_WindowClosed(event);
		}

		public void windowClosing(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == options_nbody.this)
				options_nbody_WindowClosing(event);
		}
	}
	
	void options_nbody_WindowClosing(java.awt.event.WindowEvent event)
	{
	    Store_new_Values();
		setVisible(false);
	}

	void DialogData_WindowClosed(java.awt.event.WindowEvent event)
	{
		// to do: code goes here.
			 
	}
	
	void Store_new_Values()
	{
	    // Save changed values to g
	    // body 1
	    g.m1=Double.valueOf(textField_m1.getText()).doubleValue();
	    g.X_array[0]=Double.valueOf(textField_x1.getText()).doubleValue();
	    g.X_array[1]=Double.valueOf(textField_y1.getText()).doubleValue();
	    g.X_array[2]=Double.valueOf(textField_z1.getText()).doubleValue();
	    g.X_array[3]=Double.valueOf(textField_vx1.getText()).doubleValue();
	    g.X_array[4]=Double.valueOf(textField_vy1.getText()).doubleValue();
	    g.X_array[5]=Double.valueOf(textField_vz1.getText()).doubleValue();
	    // body 2
	    g.m2=Double.valueOf(textField_m2.getText()).doubleValue();
	    g.X_array[6]=Double.valueOf(textField_x2.getText()).doubleValue();
	    g.X_array[7]=Double.valueOf(textField_y2.getText()).doubleValue();
	    g.X_array[8]=Double.valueOf(textField_z2.getText()).doubleValue();
	    g.X_array[9]=Double.valueOf(textField_vx2.getText()).doubleValue();
	    g.X_array[10]=Double.valueOf(textField_vy2.getText()).doubleValue();
	    g.X_array[11]=Double.valueOf(textField_vz2.getText()).doubleValue();
	    // body 3
	    g.m3=Double.valueOf(textField_m3.getText()).doubleValue();
	    g.X_array[12]=Double.valueOf(textField_x3.getText()).doubleValue();
	    g.X_array[13]=Double.valueOf(textField_y3.getText()).doubleValue();
	    g.X_array[14]=Double.valueOf(textField_z3.getText()).doubleValue();
	    g.X_array[15]=Double.valueOf(textField_vx3.getText()).doubleValue();
	    g.X_array[16]=Double.valueOf(textField_vy3.getText()).doubleValue();
	    g.X_array[17]=Double.valueOf(textField_vz3.getText()).doubleValue();
        // other
	    g.mu=Double.valueOf(textField_mu.getText()).doubleValue();
	    g.zoom=Double.valueOf(textField_zoom.getText()).doubleValue();
	    g.t_final=Double.valueOf(textField_tfinal.getText()).doubleValue();
	    g.t_step=Double.valueOf(textField_tstep.getText()).doubleValue();

        if(radioButton_center1.getState())  g.origin_display='1';
        if(radioButton_center2.getState())  g.origin_display='2';
        if(radioButton_center3.getState())  g.origin_display='3';
        if(radioButton_centerIRF.getState())  g.origin_display='I';
        if(radioButton_centerCM.getState())  g.origin_display='C';
        if(radioButton_nbody.getState())  g.mode='N';
        if(radioButton_crtbp.getState())  g.mode='C';
        if(radioButton_hill.getState())  g.mode='H';
        
        /*
        switch(Group_center.getSelectedCheckbox())
        {
            case radioButton_center1: g.origin_display='1';
            case radioButton_center2: g.origin_display='2';
            default: break;   
        }
        */
	}
	


	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == button_ok)
				button_ok_ActionPerformed(event);
		}
	}

	void button_ok_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		button_ok_ActionPerformed_Interaction1(event);
	}

	void button_ok_ActionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
	    Store_new_Values();
		try {
			// Dialog_options Toggle show/hide
			this.setVisible(!this.isVisible());
		} catch (java.lang.Exception e) {
		}
	}
}
